language: node_js

node_js:
  - "6"

branches:
  only:
    - master

script:
  - npm set progress=false && npm install && npm run build
  - cd dist
  - git init
  - git config user.name "Travis CI" && git config user.email "builds@travis-ci.org"
  - git remote add upstream https://$GH_TOKEN@github.com/pixelfusion/developer-docs.git
  - git fetch upstream
  - git reset upstream/gh-pages
  - git add .
  - if git diff-index --quiet HEAD; then BUILD="NO"; else BUILD="YES"; fi
  - echo "Pushing to Github Pages [$BUILD]"
  - if [ "$BUILD" == "YES" ]; then git add -A .; else true; fi
  - if [ "$BUILD" == "YES" ]; then git commit -m "Build triggered by commit $TRAVIS_COMMIT"; else true; fi
  - if [ "$BUILD" == "YES" ]; then git push -q upstream HEAD:gh-pages; else true; fi
