language: node_js

node_js:
  - '9'

branches:
  only:
    - master

script:
  - npm set progress=false && npm install && npm run build
  - cd dist
  - git init
  - git config user.name "Travis CI" && git config user.email "builds@travis-ci.org"
  - git remote add upstream https://$GH_TOKEN@github.com/kielabokkie/chmod.git
  - git fetch upstream
  - git reset upstream/gh-pages
  - git add .
  - if git diff-index --quiet HEAD; then BUILD="NO"; else BUILD="YES"; fi
  - echo "Pushing to Github Pages [$BUILD]"
  - if [ "$BUILD" == "YES" ]; then git add -A .; else true; fi
  - if [ "$BUILD" == "YES" ]; then git commit -m "Build triggered by commit $TRAVIS_COMMIT"; else true; fi
  - if [ "$BUILD" == "YES" ]; then git push -q upstream HEAD:gh-pages; else true; fi

notifications:
  slack:
    secure: owr+n8BIdinwvLLCcMiYyYnUKYk2/OZs4akwNgf+3q+Y9DcD86mT5R8J/nSLJgH4uSp5ZE4sqtfX5rDSgVvw3/aHWAXomHA344+hXEGZQCxMKbg4obrvyQy/BrTGLdLul+Ur/ZZ8P0fj3esaRHhNA2RkFZIcqa5X/GVUvoWCqR4VZC50NptOrqP3hqLcjsGYY8Q85ov6JyY4rbQl7e6Msnf6BV1MK9bKSo2wZQr2IOWW9KjZgMq8Jiz9Y/21j/Wo+YyrWNGL0XKsdVZvvunc9QW9pyRMT7QJ18ZdfFjzrItYLH9yp6th0wo8EHvAa1Uvuc3fCdPFoJCLbxyFz8HVq1726ANblNQ2Yf9F79Rklzmd7EszGBFVfOwkgH6Npb3M2wS0Jsu4IEzKmEPbIu422YqHOw0Uk8oJX4It2iedbsafYKUcgcLVvAVvzxO4X8tD8l7/6Yq2Now6dTvHSOFuePBvxrHsHVCrfa7blVh5UfTy5GvszC6HZHddAAxFhjmFvHvi7aCzGU/pZ980M9KB3rlyHXTtO2hmwf30aKiHH7GfOxXaGbcYGMYp+jE0sPx3Xgp0Dveairkbm6hoJxGZzFuVGSLpUGtkmjG2l4gkoNKVyFCGeGPS5Ksg8FTTAN5YnOVbrO2fa2fID6k+v5y8YMlg11v8r71PQB2xbigWnP0=
